export type ProjectStatus='ACTIVE'|'ON_HOLD'|'COMPLETED'|'CANCELLED';
export type FormulaStatus='DRAFT'|'TRIALLED'|'REJECTED'|'SHORTLISTED'|'APPROVED';
export type TargetStatus='MEETS_TARGET'|'CLOSE_TO_TARGET'|'OUTSIDE_TARGET'|'NO_TARGET'|'INCOMPLETE_DATA';
export interface Ingredient {ingredient_id:string;ingredient_name:string;category:string;supplier?:string;supplier_code?:string;cost_per_kg:number|null;protein_per_100g:number|null;fat_per_100g:number|null;carbohydrate_per_100g:number|null;sugar_per_100g:number|null;fibre_per_100g:number|null;moisture_per_100g:number|null;energy_kj_per_100g:number|null;allergens:string[];notes?:string;is_demo:boolean}
export interface FormulaIngredient {line_id:string;ingredient_id:string;ingredient_name:string;amount_g:number;percentage:number;cost_per_kg:number|null;line_cost:number|null;notes?:string}
export interface NutritionEstimate {energy_kj:number|null;protein:number|null;fat:number|null;carbohydrate:number|null;sugar:number|null;fibre:number|null;moisture:number|null;incomplete:boolean}
export interface FormulaVersion {formula_id:string;project_id:string;formula_version_id?:string;version_name:string;version_number:number;date_created:string;created_by?:string;batch_size_g:number;processing_yield_percent:number|null;notes?:string;status:FormulaStatus;ingredients:FormulaIngredient[];is_baseline?:boolean}
export interface ProductBrief {product_description?:string;target_serving_size_g:number|null;target_cost_per_kg:number|null;target_protein_percent:number|null;target_fat_percent:number|null;target_sugar_percent:number|null;target_moisture_percent:number|null;target_energy_kj_per_100g:number|null;target_shelf_life_days:number|null;storage_condition?:string;target_texture?:string;target_flavour?:string;target_colour?:string;target_consumer?:string;claims:string[];constraints:string[]}
export interface SensoryResponse {panelist_id:string;formula_version:string;appearance:number|null;aroma:number|null;flavour:number|null;sweetness:number|null;texture:number|null;aftertaste:number|null;overall_liking:number|null;comments?:string}
export interface SensoryTest {test_id:string;formula_id:string;test_name:string;test_date:string;panel_type:'Internal'|'Trained'|'Consumer'|'Student'|'Demonstration';number_of_panellists:number;test_method:string;notes?:string;responses:SensoryResponse[]}
export interface DevelopmentNotes {trial_observations:string;processing_issues:string;texture_observations:string;flavour_observations:string;packaging_considerations:string;open_questions:string;next_actions:string}
export interface ProductDevelopmentProject {project_id:string;workspace_id?:string;product_project_id?:string;product_id?:string;project_name:string;product_category:string;project_code:string;customer_or_brand?:string;target_market?:string;development_stage:string;project_owner?:string;start_date:string;target_launch_date?:string;project_objective?:string;target_consumer?:string;product_claims?:string[];key_constraints?:string[];allergen_notes?:string;packaging_notes?:string;processing_notes?:string;product_brief:ProductBrief;formula_versions:FormulaVersion[];sensory_tests:SensoryTest[];development_notes:DevelopmentNotes;status:ProjectStatus;created_at:string;updated_at:string;is_demo?:boolean}
