import { describe,expect,it } from 'vitest';import type { FoodQualityRecord } from '../types/quality';import { assessQuality } from '../utils/qualityAssessment';
import {defaultQualityStandards} from '../data/qualityStandards';import {cloneStandards} from '../utils/standards';
const milk=(over:Partial<FoodQualityRecord>={}):FoodQualityRecord=>({sample_id:'A',product_name:'Milk',batch_number:'B',test_date:'2026-01-01',ph:6.65,water_activity:0.85,moisture_percent:87.5,temperature_c:3,protein_percent:null,fat_percent:null,...over});
describe('assessQuality',()=>{it('returns PASS for normal sample',()=>expect(assessQuality(milk()).status).toBe('PASS'));it('returns WARNING near pH upper boundary',()=>expect(assessQuality(milk({ph:6.79})).status).toBe('WARNING'));it('treats an exact range limit as WARNING, not FAIL',()=>expect(assessQuality(milk({ph:6.8})).status).toBe('WARNING'));it('returns FAIL above pH limit',()=>expect(assessQuality(milk({ph:6.81})).status).toBe('FAIL'));it('returns WARNING at 90 percent of a maximum-only limit',()=>expect(assessQuality(milk({water_activity:0.891})).status).toBe('WARNING'));it('returns FAIL above water activity limit',()=>expect(assessQuality(milk({water_activity:1})).status).toBe('FAIL'));it('returns FAIL for physically invalid negative water activity',()=>expect(assessQuality(milk({water_activity:-0.1}))).toMatchObject({status:'FAIL',failed_parameters:['Water activity']}));it('returns INCOMPLETE with missing required value',()=>expect(assessQuality(milk({ph:null})).status).toBe('INCOMPLETE'));it('keeps a known failure visible when another required value is missing',()=>expect(assessQuality(milk({ph:null,temperature_c:99}))).toMatchObject({status:'FAIL',failed_parameters:['Temperature'],missing_parameters:['pH']}));it('deducts 25 for each failed parameter',()=>expect(assessQuality(milk({ph:7,temperature_c:8})).quality_score).toBe(50));it('never returns score below zero',()=>expect(assessQuality(milk({ph:9,water_activity:2,moisture_percent:20,temperature_c:99})).quality_score).toBe(0));it('safely marks unsupported products incomplete with no misleading score',()=>expect(assessQuality(milk({product_name:'Unknown'}))).toMatchObject({status:'INCOMPLETE',quality_score:0,missing_parameters:['Unsupported product']}))});

describe('custom product standards',()=>{
  it('changes pH warning classification when the product margin changes',()=>{const custom=cloneStandards(defaultQualityStandards);custom.Milk.warningMarginPercent=5;expect(assessQuality(milk({ph:6.78}),defaultQualityStandards)).toMatchObject({status:'WARNING',quality_score:95});expect(assessQuality(milk({ph:6.78}),custom)).toMatchObject({status:'PASS',quality_score:100})});
  it('changes maximum-only warning classification with the configured margin',()=>{const custom=cloneStandards(defaultQualityStandards);custom.Milk.warningMarginPercent=5;expect(assessQuality(milk({water_activity:0.92}),defaultQualityStandards).status).toBe('WARNING');expect(assessQuality(milk({water_activity:0.92}),custom).status).toBe('PASS')});
  it('reclassifies a previous failure after a limit is expanded',()=>{const custom=cloneStandards(defaultQualityStandards);custom.Milk.ph.max=6.9;expect(assessQuality(milk({ph:6.81})).status).toBe('FAIL');expect(assessQuality(milk({ph:6.81}),custom).status).toBe('PASS')});
  it('handles a negative maximum temperature correctly',()=>{const custom=cloneStandards(defaultQualityStandards);custom.Milk.temperature.max=-18;expect(assessQuality(milk({temperature_c:-20}),custom).status).toBe('PASS');expect(assessQuality(milk({temperature_c:-19}),custom).status).toBe('WARNING');expect(assessQuality(milk({temperature_c:-17.9}),custom).status).toBe('FAIL')});
});
