import {ArrowRight,Braces,ChartNoAxesCombined,Database,Layers3,ShieldCheck} from 'lucide-react';
import {Link} from 'react-router-dom';
import {AvailabilityPanel} from '../components/modules/AvailabilityPanel';
import {ModuleCard} from '../components/modules/ModuleCard';
import {LifecycleFlow} from '../components/workflow/LifecycleFlow';
import {SectionHeading} from '../components/ui/SectionHeading';
import {modules} from '../data/modules';
export function HomePage(){return <>
  <section className="hero"><div className="hero-grid"><div><span className="hero-kicker">Integrated food science platform</span><h1>FoodLab AI</h1><p className="hero-lead">An integrated food science platform covering product development, sensory analysis, shelf-life evaluation and production quality monitoring.</p><p className="hero-cn">食品研发、感官评价、保质期研究与质量监控的一体化食品科技平台。</p><div className="hero-actions"><Link className="button primary light" to="/modules">Explore modules <ArrowRight/></Link><Link className="button ghost-light" to="/portfolio">View portfolio</Link></div></div><div className="hero-panel"><span>Product lifecycle coverage</span><strong>4</strong><p>independent specialist applications</p><ul><li>Formula & product development</li><li>Sensory & consumer evidence</li><li>Stability & shelf-life planning</li><li>Production quality monitoring</li></ul></div></div></section>
  <section className="page-section"><SectionHeading eyebrow="Specialist modules" title="One entry point. Four focused workspaces.">Each application stays independent in Phase 1 while the Portal provides a clear, consistent route into the complete workflow.</SectionHeading><div className="module-grid">{modules.map(module=><ModuleCard key={module.id} module={module}/>)}</div><AvailabilityPanel modules={modules}/></section>
  <section className="page-section tinted"><SectionHeading eyebrow="Food product lifecycle" title="Evidence follows the product">The workflow connects formulation decisions to sensory evidence, stability evaluation and production quality feedback.</SectionHeading><LifecycleFlow compact/><div className="center-action"><Link className="text-link strong" to="/workflow">Explore the complete lifecycle <ArrowRight/></Link></div></section>
  <section className="page-section"><div className="split-intro"><SectionHeading eyebrow="Why FoodLab AI" title="Food science workflows deserve better software">The platform turns disconnected spreadsheets and calculations into transparent, structured, browser-based workflows without pretending to replace professional judgement.</SectionHeading><div className="reason-grid"><article><Layers3/><h3>Modular by design</h3><p>Each discipline keeps its own workflow, vocabulary and scientific safeguards.</p></article><article><ChartNoAxesCombined/><h3>Evidence focused</h3><p>Data, assumptions, warnings and limitations remain visible throughout.</p></article><article><ShieldCheck/><h3>Responsible scope</h3><p>Educational planning tools are clearly separated from validated approval systems.</p></article></div></div></section>
  <section className="page-section dark-section"><div className="portfolio-callout"><div><span>Portfolio platform</span><h2>Food science knowledge, expressed through working software.</h2><p>Developed by Tianyi Wang · Bachelor of Food Science · Lincoln University, New Zealand</p></div><Link className="button primary light" to="/portfolio">See project story <ArrowRight/></Link></div><div className="stack-overview"><div><Braces/><strong>React + TypeScript</strong><span>Typed, component-based interfaces</span></div><div><Database/><strong>Local-first data</strong><span>Browser storage and portable files</span></div><div><ChartNoAxesCombined/><strong>Transparent analysis</strong><span>Visual evidence with explicit limits</span></div><div><ShieldCheck/><strong>Tested workflows</strong><span>Vitest-backed domain logic</span></div></div></section>
 </>}
